export const POKEMON_TYPES = [
  { id: "todos-tipos", label: "All", icon: "🎯" },
  { id: "normal", label: "Normal", icon: "⭕" },
  { id: "fire", label: "Fire", icon: "🔥" },
  { id: "water", label: "Water", icon: "💧" },
  { id: "grass", label: "Grass", icon: "🌿" },
  { id: "electric", label: "Eletric", icon: "⚡" },
  { id: "ice", label: "Ice", icon: "❄️" },
  { id: "fighting", label: "Fighting", icon: "👊" },
  { id: "poison", label: "Poison", icon: "☠️" },
  { id: "ground", label: "Ground", icon: "🪨" },
  { id: "flying", label: "Flying", icon: "🦅" },
  { id: "psychic", label: "Psychic", icon: "🧠" },
  { id: "bug", label: "Bug", icon: "🐛" },
  { id: "rock", label: "Rock", icon: "💎" },
  { id: "ghost", label: "Ghost", icon: "👻" },
  { id: "dragon", label: "Dragon", icon: "🐉" },
  { id: "dark", label: "Dark", icon: "🌑" },
  { id: "steel", label: "Steel", icon: "⚙️" },
  { id: "fairy", label: "Fairy", icon: "✨" },
] as const;