export const typeColors: Record<string, string> = {
    fire: "bg-orange-500",
    water: "bg-blue-500",
    grass: "bg-green-500",
    electric: "bg-yellow-500",
    psychic: "bg-purple-500",
    ice: "bg-cyan-500",
    dragon: "bg-indigo-500",
    dark: "bg-gray-700",
    fairy: "bg-pink-500",
    flying: "bg-sky-500",
    poison: "bg-violet-500",
    ground: "bg-amber-700",
    rock: "bg-amber-500",
    bug: "bg-lime-600",
    ghost: "bg-purple-700",
    steel: "bg-slate-500",
    fighting: "bg-red-700",
    normal: "bg-gray-500",
  } as const;